version: '2'
services:
  oracle-exporter:
    build:
      context: .
    ports:
     - "9161:9161"
    environment:
    - DATA_SOURCE_NAME=system/password@//localhost:1521/db
    - ORACLE_DATABASE=db
    - ORACLE_INSTANCE=db

